policy_name: meta-llama/Llama-3.2-1B-Instruct
ref_name: meta-llama/Llama-3.2-1B-Instruct
precision: bf16

dataset:
  dataset_name: Anthropic/hh-rlhf
  config_name: harmless-base
  generated_data: false
  chat_template: true
  chat_template_name: llama3
  subset: train[:30%]
  eval_subset: null
  val_ratio: 0.1
  seed: 42
  max_len: 512

dpo_training:
  epochs: 1
  batch_size: 16
  eval_batch_size: 16
  learning_rate: 5e-7
  log_steps: 10
  eval_steps: 500
  save_steps: 500
  gradient_accumulation: 4
  max_grad_norm: 10
  warmup_steps: 120
  report: wandb_dpo_project
  run_name: trl-dynamic-beta-harmless-base
  save_dpo_dir: dpo_model_harmless_base
  save_dir: trl_dynamic_beta_dpo_harmless_base

sft_training:
  learning_rate: 5e-6
  batch_size: 16
  eval_batch_size: 16
  gradient_accumulation: 1
  epochs: 1
  log_steps: 10
  wandb_project: hh-harmless-base-llama32-1b-sft
  run_name: hh-harmless-base-sft
  eval_steps: 500
  save_steps: 500
  save_strategy: best
  load_best_model_at_end: true
  metric_for_best_model: eval_loss
  greater_is_better: false
  save_total_limit: 2
  warmup_steps: 120
  warmup_ratio: 0.0
  lr_scheduler_type: linear
  max_length: 512
  packing: false
  completion_only_loss: true
  save_dir: sft_model_harmless_base
  save_only_model: true
  push_to_hub: false
  hub_model_id: null
  fsdp:
    enabled: false
    mode: full_shard auto_wrap
    version: 1
    offload_params: false
    auto_wrap_policy: transformer_based_wrap
    transformer_layer_cls_to_wrap: null
    min_num_params: null
    backward_prefetch: no_prefetch
    forward_prefetch: false
    use_orig_params: true
    cpu_ram_efficient_loading: true
    sync_module_states: true
    activation_checkpointing: false
    state_dict_type: FULL_STATE_DICT

risk_test:
  delta: 0.1
  lambda: 0.1
  beta_warmup: 120

beta_update:
  beta_0: 0.1
  gamma: 2.0
  alpha: 0.005
  beta_max: 2.0
  beta_min: 0.0

margin_log:
  jsonl_sample_size: 64
  save_per_rank: false
  log_dir: logs/margins_harmless_base
  dpo_log_dir: logs/dpo_margins_harmless_base

rollout:
  engine: vllm
  vllm_batch_size: 500
  gpu_memory_utilization: 0.9
  model_name: W-61/hh-llama32-1b-sft
  output_dir: rollout_output_harmless_base
  upload_repo_id: null
  batch_size: 5
  responses_per_prompt: 5
  temperature: 0.8
  top_p: 0.9
  max_new_tokens: 256
  min_new_tokens: 10
  limit: null
  device_map: null
  judge: rm
  reward_model: RLHFlow/ArmoRM-Llama3-8B-v0.1
  reward_batch_size: 5
  reward_judge_batch_size: 5
  reward_precision: null
  reward_device_map: null
  reward_max_length: null
  reward_quantization: 8bit
  reward_load_in_8bit: false
  debug_log_path: null
  debug_log_all: false
  debug_log_empty_only: false
  debug_log_max: null
  flush_every_batches: 10
  log_throughput: true
