# Set dataset.chat_template_name: qwen3 when using Qwen/Qwen3-8B.
policy_name: princeton-nlp/Llama-3-Base-8B-SFT
precision: bf16

dataset:
  dataset_name: HuggingFaceH4/ultrachat_200k
  chat_template_name: llama3
  subset: train_sft
  eval_subset: test_sft
  val_ratio: 0.1
  seed: 42

sft_training:
  learning_rate: 6e-7
  batch_size: 2
  eval_batch_size: 4
  gradient_accumulation: 16
  epochs: 1
  log_steps: 5
  eval_steps: 400
  save_steps: 1000000
  save_strategy: steps
  load_best_model_at_end: false
  metric_for_best_model: eval_loss
  greater_is_better: false
  save_total_limit: 20
  warmup_ratio: 0.1
  lr_scheduler_type: cosine
  max_length: 2048
  packing: true
  completion_only_loss: false
  wandb_project: simpo-exps
  run_name: llama-3-8b-base-sft
  save_dir: outputs/llama-3-8b-base-sft
  save_only_model: true
  gradient_checkpointing: true
  push_to_hub: false
  hub_model_id: simpo-exps
  fsdp:
    enabled: false
    mode: full_shard auto_wrap
    version: 1
    offload_params: false
    auto_wrap_policy: transformer_based_wrap
    transformer_layer_cls_to_wrap: LlamaDecoderLayer
    min_num_params: null
    backward_prefetch: no_prefetch
    forward_prefetch: false
    use_orig_params: true
    cpu_ram_efficient_loading: true
    sync_module_states: true
    activation_checkpointing: false
    state_dict_type: FULL_STATE_DICT
