# UltraFeedback Binarized Epsilon DPO config for Qwen3 SFT.
policy_name: W-61/ultrachat-qwen3-8b-sft
ref_name: W-61/ultrachat-qwen3-8b-sft
precision: bf16

dataset:
  preference_source: ultrafeedback_binarized
  dataset_name: HuggingFaceH4/ultrafeedback_binarized
  generated_data: false
  chat_template: true
  chat_template_name: qwen3
  train_split: train_prefs
  eval_split: test_prefs
  max_len: 2048

dpo_training:
  epochs: 1
  batch_size: 1
  eval_batch_size: 1
  learning_rate: 5e-7
  log_steps: 5
  eval_steps: 300
  save_steps: 300
  gradient_accumulation: 32
  max_grad_norm: 1.0
  warmup_steps: 60
  gradient_checkpointing: true
  activation_offloading: false
  attn_implementation: flash_attention_2
  wandb_project: e_dpo
  report: null
  run_name: ultrafeedback-qwen3-8b-e-dpo
  hub_model_id: jackf857/Qwen3-8b-ultrafeedback-binarized-e-dpo
  save_dir: e_dpo_ultrafeedback_qwen_checkpoints
  save_strategy: steps
  load_best_model_at_end: false
  metric_for_best_model: eval_loss
  greater_is_better: false
  save_total_limit: 1
  save_only_model: false
  fsdp:
    enabled: true
    mode: full_shard auto_wrap
    version: 1
    offload_params: false
    auto_wrap_policy: transformer_based_wrap
    transformer_layer_cls_to_wrap: Qwen3DecoderLayer
    min_num_params: null
    backward_prefetch: no_prefetch
    forward_prefetch: false
    use_orig_params: true
    cpu_ram_efficient_loading: true
    sync_module_states: true
    activation_checkpointing: false
    state_dict_type: FULL_STATE_DICT # Critcal: DONOT use SHARDED_STATE_DICT, or saving model will fail.

e_dpo:
  beta: 0.1
  epsilon: 0.01
