policy_name: princeton-nlp/Llama-3-Instruct-8B-SimPO
precision: bf16

alpacaeval:
  pretty_name: Llama-3-Instruct-8B-SimPO
  model_name_or_path: princeton-nlp/Llama-3-Instruct-8B-SimPO
  backend: vllm
  simpo_compat: true
  use_custom_chat_template: false
  prompt_template: templates/llama3.txt
  output_dir: ../../outputs/alpacaeval/llama-3-instruct-8b-simpo
  dataset_name: tatsu-lab/alpaca_eval
  dataset_config: alpaca_eval
  dataset_split: eval
  annotators_config: weighted_alpaca_eval_gpt4_turbo
  evaluation_mode: outputs
  generation:
    batch_size: 128
    do_sample: true
    max_new_tokens: 4096
    stop_token_ids:
      - 128001
      - 128009
    temperature: 0.9
    top_p: 1.0
  vllm:
    tensor_parallel_size: 1
    trust_remote_code: false
    gpu_memory_utilization: 0.9
  transformers:
    device: cuda
    trust_remote_code: false
