Qwen3-8b-ultrafeedback-binarized-e-dpo:
  completions_kwargs:
    batch_size: 128
    do_sample: true
    max_new_tokens: 4096
    model_kwargs:
      torch_dtype: bfloat16
    model_name: jackf857/Qwen3-8b-ultrafeedback-binarized-e-dpo
    stop_token_ids:
    - 151645
    temperature: 0.9
    top_p: 1.0
  fn_completions: huggingface_local_completions
  pretty_name: Qwen3-8b-ultrafeedback-binarized-e-dpo
  prompt_template: templates/qwen3.txt
