ultrachat-llama-3-8b-sft:
  model_name: W-61/ultrachat-llama-3-8b-sft
  prompt_template: templates/ultrachat-llama-3-8b-sft.jinja
  temperature: 0.0
  max_tokens: 4096
  stop_token_ids:
    - 128001
    - 128009
  num_choices: 1
